### ISSUE TITLE
IaaS Gatewayのデータベースアクセスでエラーが起きる

### ISSUE THREAD

**Issue by ymstmsys** [primecloud-controller-org/primecloud-controller#59]
ドキュメントに従いVersion 2.6.1を新規インストールした環境において、management-tool の pcc-enable-user-aws.sh を実行すると次のエラーが発生する。

```
2016/06/25 21:28:57 [ERROR] IAAS GATEWAY ERR:AttributeError: 'MySQLConnection' object has no attribute 'get_characterset_info'
2016/06/25 21:28:57 [ERROR] キーのインポートでエラーが発生しました。keyName:user1 platformNo:1
jp.primecloud.auto.exception.AutoException: [EIAASGWP-300001] EIAASGWP-300001
        at jp.primecloud.auto.iaasgw.IaasGatewayWrapper.handleException(IaasGatewayWrapper.java:389)
        at jp.primecloud.auto.iaasgw.IaasGatewayWrapper.excGateway(IaasGatewayWrapper.java:160)
        at jp.primecloud.auto.iaasgw.IaasGatewayWrapper.describeKeyPairs(IaasGatewayWrapper.java:166)
        at jp.primecloud.auto.tool.management.iaasgw.IaasGatewayScriptService.importKeyPair(IaasGatewayScriptService.java:55)
        at jp.primecloud.auto.tool.management.main.IaasGatewayMain.importExecute(IaasGatewayMain.java:62)
        at jp.primecloud.auto.tool.management.main.Main.main(Main.java:164)
Caused by: jp.primecloud.auto.iaasgw.IaasgwException: AttributeError: 'MySQLConnection' object has no attribute 'get_characterset_info'
        at jp.primecloud.auto.iaasgw.IaasGatewayWrapper.excGateway(IaasGatewayWrapper.java:150)
        ... 4 more
```

**Comment by ymstmsys** [comment]
インストールスクリプトの中で SQLAlchemy の mysqlconnector.py を書き換えているが、コンパイル済の mysqlconnector.pyc では置き換わっていない。

次のようにコンパイルし直すことで、エラーは起きなくなった。

```
# python -m compileall -f /usr/local/lib/python2.7/site-packages/SQLAlchemy-0.7.3-py2.7-linux-x86_64.egg/sqlalchemy/dialects/mysql/mysqlconnector.py
```

**Comment by ymstmsys** [comment]
修正内容で問題がないことが確認できたので、masterにマージしました。
